//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValheimServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValheimServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string Open_Folder_Browser {
            get {
                return ResourceManager.GetString("Open_Folder_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number:.
        /// </summary>
        public static string Port_Name {
            get {
                return ResourceManager.GetString("Port_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossplay.
        /// </summary>
        public static string Server_Crossplay {
            get {
                return ResourceManager.GetString("Server_Crossplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name:.
        /// </summary>
        public static string Server_Name {
            get {
                return ResourceManager.GetString("Server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasword:.
        /// </summary>
        public static string Server_Password {
            get {
                return ResourceManager.GetString("Server_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Visible.
        /// </summary>
        public static string Server_Visibilty {
            get {
                return ResourceManager.GetString("Server_Visibilty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        public static string Start_Server {
            get {
                return ResourceManager.GetString("Start_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Steam Cmd.
        /// </summary>
        public static string Steam_Cmd_Button {
            get {
                return ResourceManager.GetString("Steam_Cmd_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Name:.
        /// </summary>
        public static string World_Name {
            get {
                return ResourceManager.GetString("World_Name", resourceCulture);
            }
        }
    }
}
