name: dotnet-desktop

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: ValheimServer.sln

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name --no-restore --configuration Release

    - name: Run StyleCop Analyzers
      run: dotnet build $env:Solution_Name --no-restore --configuration Release /p:TreatWarningsAsErrors=true
    